const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

/**
 * Build script để tự động sinh API documentation
 */

class ApiDocsBuilder {
	constructor() {
		this.rootDir = path.resolve(__dirname, "../..");
		this.scriptsDir = path.resolve(__dirname, ".");
	}

	/**
	 * Chạy tất cả các bước build
	 */
	async build() {
		console.log("🚀 Building API Documentation...\n");

		try {
			// Bước 1: Generate API content từ code (chỉ đọc JSDoc có sẵn)
			console.log("🔧 Step 1: Generating API content from existing JSDoc...");
			execSync(`node ${path.join(this.scriptsDir, "generateApiContent.js")}`, { stdio: "inherit" });
			console.log("✅ API content generated\n");

			// Bước 2: Merge với manual content
			console.log("🔗 Step 2: Merging with manual content...");
			this.mergeWithManualContent();
			console.log("✅ Content merged\n");

			// Bước 3: Validate và format
			console.log("✅ Step 3: Validating and formatting...");
			this.validateAndFormat();
			console.log("✅ Documentation built successfully!\n");

			console.log("🎉 API Documentation build completed!");
			console.log("📁 Generated files:");
			console.log("   - page/components/GeneratedApiContent.ts");
			console.log("   - page/components/ApiContent.tsx (updated)");
		} catch (error) {
			console.error("❌ Build failed:", error.message);
			process.exit(1);
		}
	}

	/**
	 * Merge generated content với manual content
	 */
	mergeWithManualContent() {
		const generatedPath = path.join(this.rootDir, "page/components/GeneratedApiContent.ts");
		const manualPath = path.join(this.rootDir, "page/components/ApiContent.tsx");

		if (!fs.existsSync(generatedPath)) {
			console.warn("⚠️  Generated content not found, skipping merge");
			return;
		}

		// Đọc generated content
		const generatedContent = fs.readFileSync(generatedPath, "utf8");
		const generatedMatch = generatedContent.match(/export const generatedApiContent = ({[\s\S]*});/);

		if (!generatedMatch) {
			console.warn("⚠️  Could not parse generated content");
			return;
		}

		const generatedApiContent = JSON.parse(generatedMatch[1]);

		// Đọc manual content
		const manualContent = fs.readFileSync(manualPath, "utf8");
		const manualMatch = manualContent.match(/const apiContent = ({[\s\S]*});/);

		if (!manualMatch) {
			console.warn("⚠️  Could not parse manual content");
			return;
		}

		let manualApiContent;
		try {
			manualApiContent = JSON.parse(manualMatch[1]);
		} catch (error) {
			console.warn("⚠️  Could not parse manual content JSON:", error.message);
			return;
		}

		// Merge content (manual overrides generated)
		const mergedContent = {
			...generatedApiContent,
			...manualApiContent,
		};

		// Tạo merged content string
		const mergedString = `// Auto-generated API content merged with manual content
// Generated on: ${new Date().toISOString()}
// Do not edit this file manually - it will be overwritten

export const apiContent = ${JSON.stringify(mergedContent, null, 2)};

// Manual overrides (these will override generated content)
export const manualOverrides = ${JSON.stringify(manualApiContent, null, 2)};
`;

		// Lưu merged content
		fs.writeFileSync(generatedPath, mergedString);
		console.log("✅ Content merged successfully");
	}

	/**
	 * Validate và format content
	 */
	validateAndFormat() {
		const generatedPath = path.join(this.rootDir, "page/components/GeneratedApiContent.ts");

		if (!fs.existsSync(generatedPath)) {
			console.warn("⚠️  Generated content not found for validation");
			return;
		}

		try {
			// Validate JSON structure
			const content = fs.readFileSync(generatedPath, "utf8");
			const match = content.match(/export const apiContent = ({[\s\S]*});/);

			if (match) {
				const apiContent = JSON.parse(match[1]);

				// Validate required fields
				const requiredFields = ["title", "description", "badges", "code"];
				let isValid = true;

				for (const [key, value] of Object.entries(apiContent)) {
					if (typeof value !== "object" || value === null) {
						console.warn(`⚠️  Invalid content for ${key}: not an object`);
						isValid = false;
						continue;
					}

					for (const field of requiredFields) {
						if (!(field in value)) {
							console.warn(`⚠️  Missing required field '${field}' in ${key}`);
							isValid = false;
						}
					}
				}

				if (isValid) {
					console.log("✅ Content validation passed");
				} else {
					console.warn("⚠️  Content validation failed - check warnings above");
				}
			}
		} catch (error) {
			console.error("❌ Validation failed:", error.message);
		}
	}

	/**
	 * Watch mode - tự động rebuild khi có thay đổi
	 */
	watch() {
		console.log("👀 Starting watch mode...");
		console.log("📁 Watching files in core/, extension/, plugins/");

		const chokidar = require("chokidar");

		const watcher = chokidar.watch(
			[
				path.join(this.rootDir, "core/src/**/*.ts"),
				path.join(this.rootDir, "extension/src/**/*.ts"),
				path.join(this.rootDir, "plugins/src/**/*.ts"),
			],
			{
				ignored: /node_modules/,
				persistent: true,
			},
		);

		let isBuilding = false;

		watcher.on("change", async (filePath) => {
			if (isBuilding) return;

			console.log(`\n📝 File changed: ${path.relative(this.rootDir, filePath)}`);
			isBuilding = true;

			try {
				await this.build();
			} catch (error) {
				console.error("❌ Watch build failed:", error.message);
			} finally {
				isBuilding = false;
			}
		});

		console.log("✅ Watch mode started. Press Ctrl+C to stop.");
	}
}

// CLI interface
if (require.main === module) {
	const builder = new ApiDocsBuilder();
	const command = process.argv[2];

	switch (command) {
		case "build":
			builder.build();
			break;
		case "watch":
			builder.watch();
			break;
		default:
			console.log("Usage: node buildApiDocs.js [build|watch]");
			console.log("  build - Build API documentation once");
			console.log("  watch - Build and watch for changes");
			process.exit(1);
	}
}

module.exports = ApiDocsBuilder;
