// Auto-generated API content
// Do not edit this file manually - it will be overwritten

export const generatedApiContent = {
  "playermanager": {
    "title": "PlayerManager",
    "description": "The PlayerManager class",
    "badges": [
      "class",
      "core",
      "playermanager"
    ],
    "code": "// PlayerManager usage example",
    "methods": [],
    "events": []
  },
  "player": {
    "title": "Player",
    "description": "The Player class",
    "badges": [
      "class",
      "core",
      "player"
    ],
    "code": "// Player usage example",
    "methods": [],
    "events": []
  },
  "queue": {
    "title": "Queue",
    "description": "The Queue class",
    "badges": [
      "class",
      "core",
      "queue"
    ],
    "code": "// Queue usage example",
    "methods": [],
    "events": []
  },
  "track": {
    "title": "Track",
    "description": "The Track interface",
    "badges": [
      "interface",
      "core",
      "track"
    ],
    "code": "// Track usage example",
    "methods": [],
    "events": []
  },
  "searchresult": {
    "title": "SearchResult",
    "description": "The SearchResult interface",
    "badges": [
      "interface",
      "core",
      "searchresult"
    ],
    "code": "// SearchResult usage example",
    "methods": [],
    "events": []
  },
  "streaminfo": {
    "title": "StreamInfo",
    "description": "The StreamInfo interface",
    "badges": [
      "interface",
      "core",
      "streaminfo"
    ],
    "code": "// StreamInfo usage example",
    "methods": [],
    "events": []
  },
  "playeroptions": {
    "title": "PlayerOptions",
    "description": "The PlayerOptions interface",
    "badges": [
      "interface",
      "core",
      "playeroptions"
    ],
    "code": "// PlayerOptions usage example",
    "methods": [],
    "events": []
  },
  "playermanageroptions": {
    "title": "PlayerManagerOptions",
    "description": "The PlayerManagerOptions interface",
    "badges": [
      "interface",
      "core",
      "playermanageroptions"
    ],
    "code": "// PlayerManagerOptions usage example",
    "methods": [],
    "events": []
  },
  "progressbaroptions": {
    "title": "ProgressBarOptions",
    "description": "Timeout in milliseconds for manager-level operations (e.g. search) when running without a Player instance. /",
    "badges": [
      "interface",
      "core",
      "progressbaroptions"
    ],
    "code": "// ProgressBarOptions usage example",
    "methods": [],
    "events": []
  },
  "extensioncontext": {
    "title": "ExtensionContext",
    "description": "The ExtensionContext interface",
    "badges": [
      "interface",
      "core",
      "extensioncontext"
    ],
    "code": "// ExtensionContext usage example",
    "methods": [],
    "events": []
  },
  "extensionplayrequest": {
    "title": "ExtensionPlayRequest",
    "description": "The ExtensionPlayRequest interface",
    "badges": [
      "interface",
      "core",
      "extensionplayrequest"
    ],
    "code": "// ExtensionPlayRequest usage example",
    "methods": [],
    "events": []
  },
  "extensionplayresponse": {
    "title": "ExtensionPlayResponse",
    "description": "The ExtensionPlayResponse interface",
    "badges": [
      "interface",
      "core",
      "extensionplayresponse"
    ],
    "code": "// ExtensionPlayResponse usage example",
    "methods": [],
    "events": []
  },
  "extensionafterplaypayload": {
    "title": "ExtensionAfterPlayPayload",
    "description": "The ExtensionAfterPlayPayload interface",
    "badges": [
      "interface",
      "core",
      "extensionafterplaypayload"
    ],
    "code": "// ExtensionAfterPlayPayload usage example",
    "methods": [],
    "events": []
  },
  "extensionstreamrequest": {
    "title": "ExtensionStreamRequest",
    "description": "The ExtensionStreamRequest interface",
    "badges": [
      "interface",
      "core",
      "extensionstreamrequest"
    ],
    "code": "// ExtensionStreamRequest usage example",
    "methods": [],
    "events": []
  },
  "extensionsearchrequest": {
    "title": "ExtensionSearchRequest",
    "description": "The ExtensionSearchRequest interface",
    "badges": [
      "interface",
      "core",
      "extensionsearchrequest"
    ],
    "code": "// ExtensionSearchRequest usage example",
    "methods": [],
    "events": []
  },
  "playerevents": {
    "title": "PlayerEvents",
    "description": "The PlayerEvents interface",
    "badges": [
      "interface",
      "core",
      "playerevents"
    ],
    "code": "// PlayerEvents usage example",
    "methods": [],
    "events": []
  },
  "sourceplugin": {
    "title": "SourcePlugin",
    "description": "/** Emitted when TTS finished (interruption mode) */ ttsEnd: []; } // Plugin interfaces",
    "badges": [
      "interface",
      "core",
      "sourceplugin"
    ],
    "code": "// SourcePlugin usage example",
    "methods": [],
    "events": []
  },
  "sourceextension": {
    "title": "SourceExtension",
    "description": "The SourceExtension interface",
    "badges": [
      "interface",
      "core",
      "sourceextension"
    ],
    "code": "// SourceExtension usage example",
    "methods": [],
    "events": []
  },
  "lavalinkext": {
    "title": "lavalinkExt",
    "description": "The lavalinkExt class",
    "badges": [
      "class",
      "core",
      "lavalinkext"
    ],
    "code": "// lavalinkExt usage example",
    "methods": [],
    "events": []
  },
  "speechoptions": {
    "title": "SpeechOptions",
    "description": "The SpeechOptions interface",
    "badges": [
      "interface",
      "core",
      "speechoptions"
    ],
    "code": "// SpeechOptions usage example",
    "methods": [],
    "events": []
  },
  "pcmstream": {
    "title": "PcmStream",
    "description": "The PcmStream class",
    "badges": [
      "class",
      "core",
      "pcmstream"
    ],
    "code": "// PcmStream usage example",
    "methods": [],
    "events": []
  },
  "voiceext": {
    "title": "voiceExt",
    "description": "The voiceExt class",
    "badges": [
      "class",
      "core",
      "voiceext"
    ],
    "code": "// voiceExt usage example",
    "methods": [],
    "events": []
  },
  "lyricsoptions": {
    "title": "LyricsOptions",
    "description": "The LyricsOptions interface",
    "badges": [
      "interface",
      "core",
      "lyricsoptions"
    ],
    "code": "// LyricsOptions usage example",
    "methods": [],
    "events": []
  },
  "lyricsresult": {
    "title": "LyricsResult",
    "description": "The LyricsResult interface",
    "badges": [
      "interface",
      "core",
      "lyricsresult"
    ],
    "code": "// LyricsResult usage example",
    "methods": [],
    "events": []
  },
  "lyricsext": {
    "title": "lyricsExt",
    "description": "The lyricsExt class",
    "badges": [
      "class",
      "core",
      "lyricsext"
    ],
    "code": "// lyricsExt usage example",
    "methods": [],
    "events": []
  },
  "youtubeplugin": {
    "title": "YouTubePlugin",
    "description": "The YouTubePlugin class",
    "badges": [
      "class",
      "core",
      "youtubeplugin"
    ],
    "code": "// YouTubePlugin usage example",
    "methods": [],
    "events": []
  },
  "soundcloudplugin": {
    "title": "SoundCloudPlugin",
    "description": "The SoundCloudPlugin class",
    "badges": [
      "class",
      "core",
      "soundcloudplugin"
    ],
    "code": "// SoundCloudPlugin usage example",
    "methods": [],
    "events": []
  },
  "spotifyplugin": {
    "title": "SpotifyPlugin",
    "description": "This minimal Spotify plugin: - Parses Spotify URLs/URIs (track/playlist/album) - Uses Spotify's public oEmbed endpoint to fetch *display metadata* (no auth, no SDK) - Does NOT provide audio streams (player is expected to redirect/fallback upstream) - Does NOT expand playlists/albums (no SDK; oEmbed doesn't enumerate items) /",
    "badges": [
      "class",
      "core",
      "spotifyplugin"
    ],
    "code": "// SpotifyPlugin usage example",
    "methods": [],
    "events": []
  },
  "ttspluginoptions": {
    "title": "TTSPluginOptions",
    "description": "The TTSPluginOptions interface",
    "badges": [
      "interface",
      "core",
      "ttspluginoptions"
    ],
    "code": "// TTSPluginOptions usage example",
    "methods": [],
    "events": []
  },
  "ttsconfig": {
    "title": "TTSConfig",
    "description": "The TTSConfig interface",
    "badges": [
      "interface",
      "core",
      "ttsconfig"
    ],
    "code": "// TTSConfig usage example",
    "methods": [],
    "events": []
  },
  "ttsplugin": {
    "title": "TTSPlugin",
    "description": "The TTSPlugin class",
    "badges": [
      "class",
      "core",
      "ttsplugin"
    ],
    "code": "// TTSPlugin usage example",
    "methods": [],
    "events": []
  }
};